# Generated by Django 4.2 on 2025-09-16 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_add_revenue_prediction_data_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(choices=[('executive', 'Executive'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('operations', 'Operations'), ('travel', 'Travel Management'), ('procurement', 'Procurement'), ('it', 'IT'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('support', 'Customer Support'), ('legal', 'Legal & Compliance'), ('other', 'Other')], default='other', max_length=20)),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('manager', 'Manager'), ('agent', 'Agent'), ('analyst', 'Analyst'), ('specialist', 'Specialist'), ('coordinator', 'Coordinator'), ('supervisor', 'Supervisor'), ('other', 'Other')], default='agent', max_length=20)),
                ('avatar', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
