# Generated by Django 4.2 on 2025-09-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_email_template_to_campaign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='api_emailte_templat_aa540d_idx',
            old_name='api_emailte_templat_a9b3e4_idx',
        ),
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='api_emailte_company_22b031_idx',
            old_name='api_emailte_company_1c5a8f_idx',
        ),
        migrations.AddField(
            model_name='rolemenupermission',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
