# Generated by Django 4.2 on 2025-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_description_to_role_menu_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadhistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Lead History'},
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='contact_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='previous_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='history_type',
            field=models.CharField(choices=[('creation', 'Lead Created'), ('note_added', 'Note Added'), ('status_change', 'Status Change'), ('score_update', 'Score Updated'), ('assignment', 'Lead Assigned'), ('contact_made', 'Contact Made'), ('call_made', 'Call Made'), ('email_sent', 'Email Sent'), ('meeting_scheduled', 'Meeting Scheduled'), ('qualification', 'Lead Qualified'), ('disqualification', 'Lead Disqualified'), ('opportunity_created', 'Opportunity Created'), ('proposal_sent', 'Proposal Sent'), ('negotiation_started', 'Negotiation Started'), ('won', 'Deal Won'), ('lost', 'Deal Lost'), ('agent_assignment', 'Agent Assignment'), ('agent_reassignment', 'Agent Reassignment'), ('contact_response', 'Contact Response'), ('phone_call_completed', 'Phone Call Completed'), ('email_response', 'Email Response'), ('meeting_completed', 'Meeting Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='icon',
            field=models.CharField(default='activity', max_length=50),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
